[project]
name = "proofhouse-python-lib"
version = "0.0.0"
description = "Reference library for the Proofhouse Python lib reference repository"
authors = [{ name = "Tony Burns", email = "tony@tonyburns.net" }]
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"
